using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GardaVettingSystem.Models
{
    /// <summary>
    /// Represents a time-limited access code generated by an applicant for a specific organisation.
    /// <para>Access codes allow organisations to retrieve an applicant's vetting data without the applicant
    /// needing to re-enter their information.</para>
    /// <para>Codes are designed to be revocable and time-limited
    /// in line with GDPR principles of integrity and confidentiality.</para>
    /// </summary>
    public class AccessCode
    {
        /// <summary>
        /// Primary key — auto-generated unique identifier for the access code record.
        /// </summary>
        [Key]
        public int AccessCodeId { get; set; }

        /// <summary>
        /// Foreign key referencing the <see cref="Applicant"/> who generated this access code.
        /// <para>Always set server-side — never accepted from form input.</para>
        /// </summary>
        [ForeignKey("Applicant")]
        public int ApplicantNumber { get; set; }

        /// <summary>
        /// Gets or sets the generated access code value.
        /// <para>Codes are 12-character alphanumeric strings generated using
        /// <see cref="System.Security.Cryptography.RandomNumberGenerator"/> for cryptographic security.</para>
        /// <para>Characters I and O are excluded to avoid visual ambiguity with digits 1 and 0.</para>
        /// <para>Always set server-side — never accepted from form input.</para>
        /// </summary>
        [Required]
        [StringLength(20, ErrorMessage = "Code cannot exceed 20 characters")]
        [Display(Name = "Access Code")]
        public string Code { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the name of the organisation this access code was generated for.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "Organisation name cannot exceed 100 characters")]
        [Display(Name = "Organisation Name")]
        public string OrganisationName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the date and time the access code was created.
        /// <para>Stored as <see cref="DateTimeOffset"/> for locale and timezone independence.</para>
        /// <para>Always set server-side to UTC at the time of generation.</para>
        /// </summary>
        [Display(Name = "Created Date")]
        public DateTimeOffset CreatedDate { get; set; } = DateTimeOffset.UtcNow;

        /// <summary>
        /// Gets or sets the date and time the access code expires.
        /// <para>Codes expire 30 days after creation by default, supporting GDPR data minimisation principles.</para>
        /// <para>A null value indicates no expiry has been set.</para>
        /// </summary>
        [Display(Name = "Expiry Date")]
        public DateTimeOffset? ExpiryDate { get; set; }

        /// <summary>
        /// Gets or sets whether this access code is currently active.
        /// <para>Set to false when the applicant revokes the code.</para>
        /// <para>Revoked codes are retained in the database rather than deleted to preserve the audit trail.</para>
        /// </summary>
        [Display(Name = "Active")]
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Navigation property — the applicant who generated this access code.
        /// </summary>
        public Applicant? Applicant { get; set; }
    }
}
