using System.ComponentModel.DataAnnotations;

namespace GardaVettingSystem.Models
{
    /// <summary>
    /// Represents an applicant's personal profile in the Garda Vetting Data Reuse System.
    /// Each registered user can have one applicant profile, which stores personal information
    /// required for Garda vetting applications. The profile can be shared with organisations
    /// via generated access codes, eliminating the need for repeated data entry.
    /// </summary>
    public class Applicant
    {
        /// <summary>
        /// Primary key — auto-generated unique identifier for the applicant profile.
        /// </summary>
        [Key]
        public int ApplicantNumber { get; set; }

        /// <summary>
        /// The ASP.NET Identity user ID of the logged-in user who owns this profile.
        /// Used to enforce ownership — each user can only access their own profile.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the applicant's first name.
        /// </summary>
        [Required(ErrorMessage = "First name is required")]
        [StringLength(50, ErrorMessage = "First name cannot exceed 50 characters")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the applicant's last name.
        /// </summary>
        [Required(ErrorMessage = "Last name is required")]
        [StringLength(50, ErrorMessage = "Last name cannot exceed 50 characters")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; } = string.Empty;

        /// <summary>
        /// Returns the applicant's full name as a concatenation of first and last name.
        /// </summary>
        public string FullName => $"{FirstName} {LastName}";

        /// <summary>
        /// Gets or sets the applicant's surname at birth, if different from their current last name.
        /// Optional field.
        /// </summary>
        [StringLength(50, ErrorMessage = "Birth surname name cannot exceed 50 characters")]
        [Display(Name = "Surname at birth")]
        public string BirthLastName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the applicant's mother's last name.
        /// Optional field required for some vetting applications.
        /// </summary>
        [StringLength(50, ErrorMessage = "Mother's last name cannot exceed 50 characters")]
        [Display(Name = "Mother's last name")]
        public string MothersLastName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the applicant's gender.
        /// </summary>
        [Required(ErrorMessage = "Gender is required")]
        [Display(Name = "Gender")]
        public string Gender { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the applicant's date of birth.
        /// Stored as <see cref="DateTimeOffset"/> rather than <see cref="DateTime"/> to ensure
        /// locale and timezone independence across different operating system regional settings.
        /// </summary>
        [Required(ErrorMessage = "Date of Birth is required")]
        [Display(Name = "Date of birth")]
        public DateTimeOffset? DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets the applicant's place of birth.
        /// Optional field.
        /// </summary>
        [StringLength(50, ErrorMessage = "Birth place cannot exceed 50 characters")]
        [Display(Name = "Place of birth")]
        public string BirthPlace { get; set; } = string.Empty;

        /// <summary>
        /// Navigation property — the collection of addresses associated with this applicant.
        /// An applicant can have multiple addresses representing their address history.
        /// </summary>
        public ICollection<ApplicantAddress> ApplicantAddresses { get; set; } = new List<ApplicantAddress>();

        /// <summary>
        /// Navigation property — the collection of access codes generated by this applicant.
        /// Access codes allow organisations to view the applicant's vetting data.
        /// </summary>
        public ICollection<AccessCode> AccessCodes { get; set; } = new List<AccessCode>();
    }

}
